Controllers/DocumentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Misericordia.Models;
using Misericordia.Data;
using System.Security.Cryptography;
using System.ComponentModel;
using Newtonsoft.Json;
using System.Text.RegularExpressions;

namespace Misericordia.Controllers
{
    public class DocumentController : Controller
    {
        internal class login{
        public string username { get; set; }
        public string password { get; set; }
    }
        public readonly MisericordiaContext _context;
        public DocumentController(MisericordiaContext context)
        {
            _context = context;
        }

        int contadorUser = 0;

public class UserAttentionViewModel
{
    public User User { get; set; }
    public Attention Attention { get; set; }
}
        public async Task<IActionResult> PriorityUser(string priority)
{
   if (!string.IsNullOrEmpty(priority))
{

    int priorityOfUser = Convert.ToInt32(priority);
    HttpContext.Session.SetInt32("priority", priorityOfUser);

    return RedirectToAction("UserNew");
}
return View();
}

        public IActionResult UserNew(string userType)
{
    if (!string.IsNullOrEmpty(userType))
    {
        HttpContext.Session.SetString("userType", userType);
        return RedirectToAction("TypeDocument"); 
       
    }
     var TypeDocumentJson = JsonConvert.SerializeObject(userType);
    return View();
}

public IActionResult TypeDocument(string TypeDocument)
{
    if (!string.IsNullOrEmpty(TypeDocument))
    {
        HttpContext.Session.SetString("typeDocument", TypeDocument);
        return RedirectToAction("EnterDocument");
    }
    return View();
}


public async Task<IActionResult> EnterDocument(string enterDocument)
{
       if (!string.IsNullOrEmpty(enterDocument)){
    enterDocument = enterDocument.Replace(" ", "");
    HttpContext.Session.SetString("enterDocument", enterDocument);
    string typeOfUser = HttpContext.Session.GetString("userType");
    string typeOfDocument = HttpContext.Session.GetString("typeDocument");
    string EnterId = HttpContext.Session.GetString("enterDocument");
    
    int documentType = Convert.ToInt32(typeOfDocument);
    int documentNumber = Convert.ToInt32(EnterId);
    

    if (typeOfUser == "2")
    {
        var user = await _context.Users
            .FirstOrDefaultAsync(u => u.DocumentType == documentType && u.DocumentNumber == documentNumber);
            
        if (user != null)
        {
            var userJson = JsonConvert.SerializeObject(user);
        HttpContext.Session.SetString("user", userJson);
            return RedirectToAction("TypeRequestUser");
        }
        else
        {
            return RedirectToAction("ErrorDocument");
        }
    }
    else
    {
            Console.WriteLine("aqui el usuario no lo tenemos registrado");
            var user = await _context.Users
            .FirstOrDefaultAsync(u => u.DocumentType == 5 && u.DocumentNumber == 0);
             var userJson = JsonConvert.SerializeObject(user);
             HttpContext.Session.SetString("user", userJson);
        return RedirectToAction("TypeRequestNewUser");

    } 
    }  
    return View();
}

public IActionResult TypeRequestUser(string typeRequest)
{
    if (!string.IsNullOrEmpty(typeRequest))
    
    {
        HttpContext.Session.SetString("typeRequest", typeRequest);
            
            
            return RedirectToAction("Ficho");
    }
    return View();
}

public IActionResult TypeRequestNewUser(string typeRequestNew)
{
    if (!string.IsNullOrEmpty(typeRequestNew))
    {
        HttpContext.Session.SetString("typeRequest", typeRequestNew);
        
        return RedirectToAction("Ficho");
    }
   

    return View();
}

public IActionResult ErrorDocument()
{
    return View();
}

public IActionResult Gestion()
{
    var turns = from atention in _context.Attentions join
    employee in _context.Employees on atention.EmployeeId equals employee.Id select new {modulo = employee.Modulo, turno = atention.NumAttention, estado = atention.Status};
    return View(turns);
}

[HttpPost]
public async Task<IActionResult> Ficho(string? typeRequest)
{
    string typeOfUser = HttpContext.Session.GetString("userType");
    
    if (!string.IsNullOrEmpty(typeRequest))
    {
        ViewBag.typeOfRequest = typeRequest;
    }
    var fichos = from consulta in _context.Attentions select consulta;
    string newTurn = "";
    int turno = 1;
    if (typeRequest == "1")
    {
        ViewBag.typeOfRequest = "GC";
        foreach(var item in fichos){
        if("GC" == Regex.Match(item.NumAttention, @"\w+").Value){

                int number = int.Parse(Regex.Match(item.NumAttention, @"\d+").Value);
                turno = number + 1;
            }
    }

    }
    else if (typeRequest == "2")
    {
        ViewBag.typeOfRequest = "IF";
        foreach(var item in fichos){
        if("IF" == Regex.Match(item.NumAttention, @"\w+").Value){

                int number = int.Parse(Regex.Match(item.NumAttention, @"\d+").Value);
                turno = number + 1;
            }
    }
    }
    else if (typeRequest == "3")
    {
        ViewBag.typeOfRequest = "PF";
        foreach(var item in fichos){
        if("PF" == Regex.Match(item.NumAttention, @"\w+").Value){

                int number = int.Parse(Regex.Match(item.NumAttention, @"\d+").Value);
                turno = number + 1;
            }
    }

    }
    else if (typeRequest == "4")
    {
        ViewBag.typeRequest = "AM";
        foreach(var item in fichos){

        if("AM" == Regex.Match(item.NumAttention, @"\w+").Value){

                int number = int.Parse(Regex.Match(item.NumAttention, @"\d+").Value);
                turno = number + 1;
            }
    }
    }

    string typeOfDocument = HttpContext.Session.GetString("typeDocument");

    if (typeOfDocument == "1")
    {
        ViewBag.typeOfDocument = "CC";
    }
    else if (typeOfDocument == "2")
    {
        ViewBag.typeOfDocument = "TI";
    }
    else if (typeOfDocument == "3")
    {
        ViewBag.typeOfDocument = "CE";
    }
    else if (typeOfDocument == "4")
    {
        ViewBag.typeOfDocument = "DA";
    }

    var userJson = HttpContext.Session.GetString("user");
    var user = JsonConvert.DeserializeObject<User>(userJson);

    

    newTurn = ViewBag.typeOfRequest + "-" + turno;
    ViewBag.newTurn = newTurn;
    ViewBag.document= HttpContext.Session.GetString("enterDocument");
    var attention = new Attention
    {
        NumAttention = newTurn,
        UserId = user.Id,
        DateAttentionEnter = DateTime.Now,
        AttentionPreference = HttpContext.Session.GetInt32("priority"),
        Status = "ESPERA"
    };

    _context.Attentions.Update(attention);
    await _context.SaveChangesAsync();

     var viewModel = new UserAttentionViewModel
    {
        User = user,
        Attention = attention
    };

    return View(viewModel);
}
}
  } 

Views/Document/EnterDocument.cshtml
@model User

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/stylesDocument.css" asp-append-version="true" />
    <title>Document</title>
</head>

<body>
    <div class="main">
        <div class="main2">
            <div class="container mb-2">
                <div class="img">
                    <a class="navbar-brand" href="#">
                        <img src="https://static1.squarespace.com/static/5750d1ba2b8dde8ea7454e58/57aa9a018419c2428e61eeff/5a006c50085229970597cf1c/1533612260646/Misericordia+logo+1.jpg?format=1500w"
                            class="mt-2" alt="Misericordia" width="160px" height="112px">
                    </a>
                </div>
                <div class="title">
                    <h1 class="text-center">Bienvenido al sistema de turnos</h1>
                    <h3 class="text-center mb-5">Ingrese su documento</h3>
                </div>

            </div>




            <p>@ViewBag.mensaje</p>

            <form asp-action="EnterDocument" method="post" class="form">
                <div class="input2">

                    <div class="subscribe form-floating">
                        <h2 class="text-center ">Toma tu turno</h2>
                        <input type="text" class="input form-control" id="Documento"  name="enterDocument"  placeholder="Identificacion">
                    </div>

                </div>


                <div class="body">
                    <div class="display d-block">

                        <div class="btn-group b" role="group" aria-label="Basic example">
                            <button type="button" class="btn btn-secondary a" id="btn_7">7</button>
                            <button type="button" class="btn btn-secondary a" id="btn_8">8</button>
                            <button type="button" class="btn btn-secondary a" id="btn_9">9</button>
                        </div>
                        <div class="btn-group b" role="group" aria-label="Basic example">
                            <button type="button" class="btn btn-secondary a" id="btn_4">4</button>
                            <button type="button" class="btn btn-secondary a" id="btn_5">5</button>
                            <button type="button" class="btn btn-secondary a" id="btn_6">6</button>
                        </div>
                        <div class="btn-group b" role="group" aria-label="Basic example">
                            <button type="button" class="btn btn-secondary a" id="btn_1">1</button>
                            <button type="button" class="btn btn-secondary a" id="btn_2">2</button>
                            <button type="button" class="btn btn-secondary a" id="btn_3">3</button>
                        </div>
                        <div class="btn-group b" role="group" aria-label="Basic example">
                            <button type="button" class="btn btn-secondary a" id="btn_Clear">Borrar</button>
                            <button type="button" class="btn btn-secondary" id="btn_0">0</button>
                            <button type="submit" class="btn btn-secondary" >OK</button>
                        </div>
                    </div>
                </div>
            <a id="flecha" class="btn btn-secondary" asp-action="TypeDocument" asp-controller="Document">
                <img class="flecha" src="https://cdn-icons-png.flaticon.com/512/1/1453.png" alt="">
            </a>
            </form>
        </div>

    </div>
    
     

    <p>@ViewBag.mensaje</p>
    <footer>
        <script src="~/js/EnterDocument.js" asp-append-version="true"></script>
    </footer>
</body>

</html>

Views/Document/ErrorDocument.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/stylesDocument.css" asp-append-version="true" />
    <title>Document</title>
</head>
<body>
    <div class="container mb-2">
    <div class="img">
        <a class="navbar-brand" href="#">
            <img src="https://static1.squarespace.com/static/5750d1ba2b8dde8ea7454e58/57aa9a018419c2428e61eeff/5a006c50085229970597cf1c/1533612260646/Misericordia+logo+1.jpg?format=1500w"
                alt="Misericordia" width="80px" height="56px">
        </a>
    </div>
    <div class="title">
        <h1 class="text-center">lo siento parece que tuviste un error al ingresar los datos de tu documento por favor vuelve a ingresarlos</h1>
    </div>
</div>

    <form asp-action="UserNew" method="post" class="form">


    <div class="group-buttons ">
        <div class="contenedor">
            <button type="submit" class="btn btn-success" >Volver a ingresar</button>
        </div>
    </div>

</form>
</body>
</html>

Views/Document/Ficho.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body onload="reload()">
    <div class="container">
        <div>
            <h1>Bienvenido a la eps la misericordia @Model.User.Firstname @Model.User.Lastname</h1>
        </div>
        <div>
            <h2>Su turno es: @ViewBag.newTurn</h2>
            <h2>N° Documento: @ViewBag.typeOfDocument.@ViewBag.document</h2>
        </div>
    </div>
</body>

<script>
    function reload(){
        setTimeout(()=>{

        location.href = "http://localhost:5191/"
        }, 5000)
    }
</script>

</html>

Views/Document/Gestion.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body class="Body-gestion ">

  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true"
    style="display: block;">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Siguiente turno</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body" id="mensajes">
        </div>
        <div class="modal-footer">
        </div>
      </div>
    </div>
  </div>


  <div class="container-Gestion row  ">

    <h1 class="text-center mb-5">Todos Los Turnos</h1>
    <div class="col-md-6 overflow-scroll table-margin" style="max-height: 700px; max-width: 600px;">
      <table class=" table table-bordered  table-hover table-dark  w-48 h-64 rounded-lg border-red">
        <thead class="z-3">
          <tr>
            <th scope="col">Modulo</th>
            <th scope="col">Turno</th>
          </tr>
        </thead>
        <tbody id="tbody">
          @foreach (var item in Model)
          {
            if (item.estado == "ATENDIENDO" || item.estado == "LLAMANDO")
            {
              <tr id="@item.turno">
                <td scope="row">@item.modulo</td>
                <td>@item.turno</td>
              </tr>
            }
          }


        </tbody>
      </table>


    </div>

    <div class="  col-md-6 ">
      <div class="card card-position" style="width: 38rem; height:40rem;">
        <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img src="https://lh3.googleusercontent.com/oT9tiy8zRPMIc7kXflyqN6lAM-EVBtzf9RzJQTz93vNa61fSYxgRBaYUm60a5MGBeKUPlX0aGG42PIOLooVSm1sI0A5tDraoV7yW0F49PUD8UTquPFl-4Nt1VVb4h2a1MpltQ0tAI7s3hnSDklZBHy4" alt="..." width="600rem"
                height="400rem">
            </div>
            <div class="carousel-item">
              <img src="https://i.insider.com/60f861f50729770012b91ccd?width=1136&format=jpeg" alt="..." width="600rem"
                height="400rem">
            </div>
            <div class="carousel-item">
              <img src="https://coosalud.com/wp-content/uploads/2019/12/saludvida-a-acoosalud-02.jpg" alt="..."
                width="600rem" height="400rem">
            </div>
            <div class="carousel-item">
              <img src="https://epswater.ie/wp-content/uploads/2020/12/EPS-Site-Logo-01.png" alt="..." width="900rem"
                height="400rem">
            </div>
          </div>
        </div>
        <div class="card-body">
          <h5 class="card-title text-center">Notificacion</h5>

          <p class="card-text ">Tu turno esta identificado con las letras de tu typo de turno y el numero es el turno.
          </p>
          <div class="alert alert-warning alerta text-center" role="alert ">
            Preferencias a personas discapacitadas,niños o mujeres en embarazo.
          </div>
        </div>
      </div>






    </div>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/@@microsoft/signalr@5.0.8/dist/browser/signalr.min.js"></script>
  <script>

    const connection = new signalR.HubConnectionBuilder()
      .withUrl("/chatHub")
      .build();

    connection.on("NuevoMensaje", (usuario, mensaje) => {
      $('#mensajes').append(`<h4><strong>${usuario}:</strong> modulo: ${mensaje}</h4>`);
      $('#' + usuario).remove();
      $('#tbody').append(`
         <tr id="${usuario}">
            <th scope="row">${mensaje}</th>
            <td>${usuario}</td>
          </tr>`);
    });

    connection.on("Limpiar", (id) => {
      $('#' + id).remove();
    });

    connection.start().then(() => {
      console.log('Conectado al servidor SignalR');
    }).catch(err => console.error(err.toString()));

    function enviarMensaje(sms, empleado) {
      const usuario = sms
      const mensaje = empleado
      connection.invoke("EnviarMensaje", usuario, mensaje);
      verificarContenidoDiv();
      $('#mensaje').val('');
    }
    function Limpiar() {
      connection.invoke("Limpiar");
    }

    function reproducirSonido() {
      var sonido = new Audio('/archivos/notificacion.mp3');
      sonido.play();
    }


    function verificarContenidoDiv() {
      var div = document.getElementById('mensajes');
      let modal = document.getElementById("exampleModal");
      console.log(div.innerHTML);
      if (div.innerHTML == '') {
        modal.style.display = 'none';
        modal.classList.remove("show");
      } else {
        modal.style.display = 'block';
        modal.classList.add("show");
        reproducirSonido();
        setTimeout(function () {
          div.innerHTML = ''; // Borrar el contenido
          modal.style.display = 'none'; // Ocultar el div nuevamente
        }, 4000);
      }
    }
    // Ejecutar la función cada 5 segundos
    setInterval(verificarContenidoDiv, 5000);
  </script>

</body>

</html>

Views/Document/InformaciongR.cshtml
<link rel="stylesheet" href="~/css/InfoGNRL.css" />
 
  <div class="container">
  <img class="saturno" src="https://cdn-icons-png.flaticon.com/512/788/788268.png" alt="">
  
  <h1 class="titulo">Bienvenido al sistema de turnos</h1>


  <h2 class="suptitulo">Seleccione su tipo de solicitud</h2>

  <div class="contenedor2">
    <img class="saturno2" src="https://cdn-icons-png.flaticon.com/512/788/788268.png" alt="">
    <h3>Su turno es: @Model.turnos</h3>
    <h3>N° Documento @Model.DocumentType @Model.DocumentNumber</h3>
  </div>

  </div>

Views/Document/PriorityUser.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/stylesDocument.css" asp-append-version="true" />
    <title>Document</title>
</head>
<body>
    <div class="container mb-2">
    <div class="img">
        <a class="navbar-brand" href="#">
            <img src="https://static1.squarespace.com/static/5750d1ba2b8dde8ea7454e58/57aa9a018419c2428e61eeff/5a006c50085229970597cf1c/1533612260646/Misericordia+logo+1.jpg?format=1500w"
                alt="Misericordia" width="80px" height="56px">
        </a>
    </div>

    <h3 class="text-center mb-5">Seleccione su tipo de atencion</h3>


<form asp-action="PriorityUser" method="post" class="form">
    <div class="group-buttons ">
        <div class="contenedor">
            <button type="submit" class="btn btn-success" name="priority" value="1"> Preferencial</button>
        </div>
        <div class="contenedor">
            <button type="submit" class="btn btn-success" name="priority" value="2"> No preferencial</button>
        </div>
    </div>
</form>
</body>
</html>



</body>
</html>

Views/Document/TypeDocument.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/stylesDocument.css" asp-append-version="true" />
    <title>Document</title>
</head>

<body class="Body-Type-Document ">
    <div class="container-Type-Document mb-2 ">
        <div class="img">
            <a class="navbar-brand" href="#">
                <img src="https://static1.squarespace.com/static/5750d1ba2b8dde8ea7454e58/57aa9a018419c2428e61eeff/5a006c50085229970597cf1c/1533612260646/Misericordia+logo+1.jpg?format=1500w"
                    class="mt-2" alt="Misericordia" width="160px" height="112px">
            </a>
        </div>
        <div class="title">
            <h1 class="text-center">Bienvenido al sistema de turnos</h1>




    <h3 class="text-center mb-5">Seleccione su tipo de documento</h3>

  <h1>@ViewBag.mensaje</h1>
  <h1>@ViewBag.mensaje2</h1>
    <form asp-action="TypeDocument" method="post" class="form">
    <div class="group-buttons ">
        <div class="contenedor">
            <button type="submit" class="btn btn-success" name="typeDocument" value="1"> Cedula</button>
        </div>
        <div class="contenedor">
            <button type="submit" class="btn btn-success" name="typeDocument" value="2"> Tarjeta de identidad</button>
        </div>
        <div class="contenedor">
            <button type="submit" class="btn btn-success" name="typeDocument" value="3">Cedula extrajera</button>
        </div>
        <div class="contenedor">
            <button type="submit" class="btn btn-success" name="typeDocument" value="4">Carné de Afiliación a la EPS</button>
        </div>
    </div>
</form>
</body>

</html>


<footer>
    <script src="~/js/typeDocument.js" asp-append-version="true"></script>
</footer>

Views/Document/TypeRequestNewUser.cshtml
<link rel="stylesheet" href="~/css/solicitudNRG.css" />

<div class="container">
    <img class="saturno" src="https://cdn-icons-png.flaticon.com/512/788/788268.png" alt="">
    <h1 class="titulo">Bienvenido al sistema de turnos</h1>
    <h2 class="suptitulo">Seleccione su tipo de solicitud</h2>
    <div class="row">
        <div class="col-sm-12 mb-3 mb-sm-0">
            <div class="card">
                <form asp-action="Ficho" method="post" class="form">
                <div class="card-body">
                    <button type="submit" class="btn btn-secondary" id="btn_4" value="2" name="typeRequest">Informacion general</button>
                </div>
                </form>
                <a id="flecha" class="btn btn-secondary" asp-action="EnterDocument" asp-controller="Document"><img class="flecha" src="https://cdn-icons-png.flaticon.com/512/1/1453.png" alt=""></a>
                
            </div>
        </div>
    </div>
</div>

Views/Document/TypeRequestUser.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="~/css/solTurno.css" />
</head>
<body>
    <div class="container">
        <img class="saturno" src="https://cdn-icons-png.flaticon.com/512/788/788268.png" alt="">
        <h1 class="titulo">Bienvenido al sistema de turnos</h1>
        <h2 class="suptitulo">Seleccione su tipo de solicitud</h2>

<<<<<<< HEAD








        <div class="row">
            <div class="col-sm-6 mb-3 mb-sm-0">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="card">
                                    <div class="card-body">
                                        <a class="btn btn-primary" id="btn_1" value="1" type="submit"><h2>Gestión de Cita
                                            Medica</h2></a>

=======
        <form asp-action="EnterDocument" method="post" class="form">
            <div class="row">
                <div class="col-sm-6 mb-3 mb-sm-0">
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="card">
                                        <div class="card-body">
<button type="submit" class="btn btn-success" name="typeRequest" value="1" asp-controller="Document" asp-action="Ficho">Gestión de Cita Medica</button>                                        </div>
>>>>>>> d9ffe05c23ee167e70a17d594d2422a63e113230
                                    </div>
                                </div>

<<<<<<< HEAD
                            <div class="col-sm-12">
                                <div class="card">
                                    <div class="card-body">
                                        <a class="btn btn-warning" id="btn_2" value="2" type="submit"><h2>Informacion
                                            general</h2></a>
=======
                                <div class="col-sm-12">
                                    <div class="card">
                                        <div class="card-body">
                                            <button type="submit" class="btn btn-success" name="typeRequest" value="2" asp-controller="Document" asp-action="Ficho">Informacion general</button>
                                        </div>
>>>>>>> d9ffe05c23ee167e70a17d594d2422a63e113230
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

<<<<<<< HEAD
            <div class="col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="card">
                                    <div class="card-body">
                                        <a class="btn btn-success" id="btn_3" value="3" type="submit"><h2>Pago Factura</h2></a>
=======
                <div class="col-sm-6">
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="card">
                                        <div class="card-body">
                                            <button type="submit" class="btn btn-success" name="typeRequest" value="3" asp-controller="Document" asp-action="Ficho">Pago Factura</button>
                                        </div>
>>>>>>> d9ffe05c23ee167e70a17d594d2422a63e113230
                                    </div>
                                </div>

<<<<<<< HEAD
                            <div class="col-sm-12">
                                <div class="card">
                                    <div class="card-body">
                                        <a class="btn btn-info" id="btn_4" value="4" type="submit"><h2>Autorización de
                                            medicamentos</h2></a>
=======
                                <div class="col-sm-12">
                                    <div class="card">
                                        <div class="card-body">
                                            <button type="submit" class="btn btn-success" name="typeRequest" value="4" asp-controller="Document" asp-action="Ficho">Autorización de medicamentos</button>
                                        </div>
>>>>>>> d9ffe05c23ee167e70a17d594d2422a63e113230
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>

        <a id="flecha" class="btn btn-secondary" asp-action="EnterDocument" asp-controller="Document">
            <img class="flecha" src="https://cdn-icons-png.flaticon.com/512/1/1453.png" alt="">
        </a>
    </div>
</body>
</html>

Views/Document/UserNew.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/stylesDocument.css" asp-append-version="true" />
    <title>Document</title>
</head>
<body>
    <div class="container mb-2">
    <div class="img">
        <a class="navbar-brand" href="#">
            <img src="https://static1.squarespace.com/static/5750d1ba2b8dde8ea7454e58/57aa9a018419c2428e61eeff/5a006c50085229970597cf1c/1533612260646/Misericordia+logo+1.jpg?format=1500w"
                alt="Misericordia" width="80px" height="56px">
        </a>
    </div>
<h1>@ViewBag.mensaje2</h1>
    <h3 class="text-center mb-5">Que tipo de usuario eres</h3>


<form asp-action="userNew" method="post" class="form">
    <div class="group-buttons ">
        <div class="contenedor">
            <button type="submit" class="btn btn-success" name="userType" value="1"> usuario nuevo</button>
        </div>
        <div class="contenedor">
            <button type="submit" class="btn btn-success" name="userType" value="2"> Usuario cotizanote</button>
        </div>
    </div>
</form>
</body>
</html>